name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    strategy:
      matrix:
        phpVersion: [ "5.6", "7.1", "7.2", "7.4", "8.0", "8.1", "8.2" ]
        include:
          - phpVersion: '5.6'
            extMysql: 'mysql'
            extension: 'gd redis-4.3.0 swoole-2.0.11'
            extEnable: 'redis swoole'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm64/v8,linux/ppc64le'
          - phpVersion: '7.1'
            extMysql: ''
            extension: 'gd redis-4.3.0 swoole-4.5.11 xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          - phpVersion: '7.2'
            extMysql: ''
            extension: 'gd redis-4.3.0 swoole-4.8.13 xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          - phpVersion: '7.4'
            extMysql: ''
            extension: 'gd redis-4.3.0 swoole-4.8.13 xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          - phpVersion: '8.0'
            extMysql: ''
            extension: 'gd redis swoole xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          - phpVersion: '8.1'
            extMysql: ''
            extension: 'gd redis swoole xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
          - phpVersion: '8.2'
            extMysql: ''
            extension: 'gd redis swoole xlswriter'
            extEnable: 'redis swoole xlswriter'
            supportArch: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=php:${{ matrix.phpVersion }}-fpm-alpine
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.supportArch }}
          push: true
          tags: jjonline/docker-php-runtime:${{ matrix.phpVersion }}-fpm-alpine-${{ steps.meta.outputs.version }},jjonline/docker-php-runtime:${{ matrix.phpVersion }}-fpm-alpine
          build-args: |
            phpVersion=${{ matrix.phpVersion }}
            extMysql=${{ matrix.extMysql }}
            extension=${{ matrix.extension }}
            extEnable=${{ matrix.extEnable }}
